---
title: Shiny in Markdown
author: Jared P. Lander
output: html_document
runtime: shiny
---

# Testing Testing

1, 2, 3

# Select Input

```{r select-input}
selectInput(
    inputId='StateSelection',
    label='Please choose a state',
    choices=list('NY', 'NJ', 'MA', 'RI', 'TX'),
    selected='MA'
)
```

```{r print-state}
renderText(input$StateSelection)
```

# Other Inputs

```{r other-inputs}
sliderInput(
    inputId='SliderSample',
    label='This is a slider',
    min=0, max=10, value=5
)

checkboxInput(
    inputId='CheckSample',
    label='Check This'
)

radioButtons(
    inputId='RadioSample',
    label='Choose one',
    choices=list('AB', 'A', 'B', 'O')
)

dateInput(
    inputId='DateChoice',
    label='Select a date'
)

dateRangeInput(
    inputId='DateRangeChoice',
    label='Choose your dates'
)
```

# Text Input

```{r text-input}
textInput(
    inputId='TextSample',
    label='Write Something',
    placeholder='Write on the ghost'
)

textAreaInput(
    inputId='TextAreaSample',
    label='Write a long passage'
)

passwordInput(
    inputId='PasswordSample',
    label='Enter the secret'
)

renderText(input$PasswordSample)
```

# Show Data

```{r render-tables}
renderTable(mtcars)

renderDataTable(mtcars)

DT::renderDataTable(mtcars)
```

